/**
 * Cross-links to other vertical sites in the network.
 * Auto-generated by the verticals hub sync-crosslinks script.
 * Do NOT edit manually.
 */

export interface CrossLink {
  name: string;
  domain: string;
  url: string;
  tagline: string;
}

// --- SCAFFOLD REPLACES BELOW ---
export const crosslinks: CrossLink[] = [];
