/**
 * Vertical Configuration — Single source of truth for this vertical site.
 * Generated by the verticals hub scaffold script from registry/{slug}.json.
 * Do NOT edit manually — re-run the scaffold to update.
 */

export interface VerticalConfig {
  slug: string;
  brandName: string;
  domain: string;
  tagline: string;
  description: string;

  agent: {
    publicId: string | null;
    backendUrl: string;
    widgetUrl: string;
    phoneNumber: string | null;
  };

  theme: {
    primary: string;
    accent: string;
    success: string;
    warning: string;
  };

  industry: {
    name: string;
    shortName: string;
    avgTicket: string;
    painPoint: string;
    projectTypes: string[];
    commonSoftware: string[];
    leadSources: string[];
  };

  seo: {
    primaryKeywords: string[];
    metaPixelId: string | null;
  };

  social: Record<string, string>;
  calcomLink: string | null;
  relatedVerticals: Array<{
    name: string;
    domain: string;
    slug: string;
  }>;
}

// --- SCAFFOLD REPLACES BELOW ---
export const config: VerticalConfig = {
  slug: "TEMPLATE",
  brandName: "TEMPLATE",
  domain: "example.com",
  tagline: "AI Receptionist for Your Industry",
  description: "AI-powered receptionist that answers calls, qualifies leads, and books appointments 24/7.",

  agent: {
    publicId: null,
    backendUrl: "https://backend-api-production-b536.up.railway.app",
    widgetUrl: "https://backend-api-production-b536.up.railway.app/widget/v1/widget.js",
    phoneNumber: null,
  },

  theme: {
    primary: "#2563EB",
    accent: "#3B82F6",
    success: "#10B981",
    warning: "#F59E0B",
  },

  industry: {
    name: "Your Industry",
    shortName: "Pros",
    avgTicket: "$5,000 - $15,000",
    painPoint: "Missing calls means losing jobs to competitors who answer first",
    projectTypes: [],
    commonSoftware: [],
    leadSources: [],
  },

  seo: {
    primaryKeywords: [],
    metaPixelId: null,
  },

  social: {},
  calcomLink: null,
  relatedVerticals: [],
};
