#!/usr/bin/env tsx
/**
 * Scaffold a new vertical site from the template.
 *
 * Usage: tsx scripts/scaffold.ts <slug>
 * Example: tsx scripts/scaffold.ts painters
 */

import { execSync } from "child_process";
import { cpSync, existsSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";
import { loadVerticalConfig, loadVerticalsIndex, HUB_ROOT } from "./lib/config";

const slug = process.argv[2];

if (!slug) {
  console.error("Usage: tsx scripts/scaffold.ts <slug>");
  console.error("Example: tsx scripts/scaffold.ts painters");
  process.exit(1);
}

console.log(`\n🔧 Scaffolding vertical: ${slug}\n`);

// 1. Load and validate config
console.log("1. Loading config...");
const config = loadVerticalConfig(slug);
console.log(`   Brand: ${config.brandName}`);
console.log(`   Domain: ${config.domain}`);
console.log(`   Repo: ${config.repoDir}`);

// 2. Check if directory already exists
if (existsSync(config.repoDir)) {
  console.error(`\n   ERROR: Directory already exists: ${config.repoDir}`);
  console.error("   Remove it first or use a different slug.");
  process.exit(1);
}

// 3. Copy template
console.log("2. Copying template...");
const templateDir = join(HUB_ROOT, "template");
cpSync(templateDir, config.repoDir, { recursive: true });

// 4. Write vertical.config.ts
console.log("3. Writing vertical.config.ts...");
const verticalConfigContent = `/**
 * Vertical Configuration — Single source of truth for this vertical site.
 * Generated by the verticals hub scaffold script from registry/${slug}.json.
 * Do NOT edit manually — re-run the scaffold to update.
 */

export interface VerticalConfig {
  slug: string;
  brandName: string;
  domain: string;
  tagline: string;
  description: string;

  agent: {
    publicId: string | null;
    backendUrl: string;
    widgetUrl: string;
    phoneNumber: string | null;
  };

  theme: {
    primary: string;
    accent: string;
    success: string;
    warning: string;
  };

  industry: {
    name: string;
    shortName: string;
    avgTicket: string;
    painPoint: string;
    projectTypes: string[];
    commonSoftware: string[];
    leadSources: string[];
  };

  seo: {
    primaryKeywords: string[];
    metaPixelId: string | null;
  };

  social: Record<string, string>;
  calcomLink: string | null;
  relatedVerticals: Array<{
    name: string;
    domain: string;
    slug: string;
  }>;
}

export const config: VerticalConfig = ${JSON.stringify(
  {
    slug: config.slug,
    brandName: config.brandName,
    domain: config.domain,
    tagline: config.tagline,
    description: config.description,
    agent: {
      publicId: config.agent.publicId,
      backendUrl: config.agent.backendUrl,
      widgetUrl: `${config.agent.backendUrl}/widget/v1/widget.js`,
      phoneNumber: config.agent.phoneNumber,
    },
    theme: config.theme,
    industry: config.industry,
    seo: {
      primaryKeywords: config.seo.primaryKeywords,
      metaPixelId: config.seo.metaPixelId,
    },
    social: config.social,
    calcomLink: config.calcomLink,
    relatedVerticals: config.relatedVerticals,
  },
  null,
  2
)};
`;
writeFileSync(
  join(config.repoDir, "src", "lib", "vertical.config.ts"),
  verticalConfigContent
);

// 5. Update package.json name
console.log("4. Updating package.json...");
const pkgPath = join(config.repoDir, "package.json");
const pkg = JSON.parse(readFileSync(pkgPath, "utf-8"));
pkg.name = `vertical-${slug}`;
writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + "\n");

// 6. Write .env.local
console.log("5. Writing .env.local...");
writeFileSync(
  join(config.repoDir, ".env.local"),
  `BACKEND_URL=${config.agent.backendUrl}\nAGENT_PUBLIC_ID=${config.agent.publicId || ""}\nSITE_DOMAIN=${config.domain}\n`
);

// 7. Generate crosslinks.ts
console.log("6. Generating crosslinks.ts...");
const crosslinksContent = `/**
 * Cross-links to other vertical sites in the network.
 * Auto-generated by the verticals hub sync-crosslinks script.
 * Do NOT edit manually.
 */

export interface CrossLink {
  name: string;
  domain: string;
  url: string;
  tagline: string;
}

export const crosslinks: CrossLink[] = ${JSON.stringify(
  config.relatedVerticals.map((v) => ({
    name: v.name,
    domain: v.domain,
    url: `https://${v.domain}`,
    tagline: "",
  })),
  null,
  2
)};
`;
writeFileSync(
  join(config.repoDir, "src", "lib", "crosslinks.ts"),
  crosslinksContent
);

// 8. Git init
console.log("7. Initializing git...");
execSync("git init", { cwd: config.repoDir, stdio: "pipe" });
writeFileSync(
  join(config.repoDir, ".gitignore"),
  `node_modules/\n.next/\n.source/\n.env.local\n.vercel/\n`
);

// 9. npm install
console.log("8. Installing dependencies (this may take a minute)...");
execSync("npm install", { cwd: config.repoDir, stdio: "inherit" });

// 10. Typecheck and build
console.log("9. Running typecheck...");
try {
  execSync("npm run typecheck", { cwd: config.repoDir, stdio: "inherit" });
} catch {
  console.error("\n   WARNING: Typecheck failed. Fix errors before deploying.");
}

console.log("10. Running build...");
try {
  execSync("npm run build", { cwd: config.repoDir, stdio: "inherit" });
} catch {
  console.error("\n   WARNING: Build failed. Fix errors before deploying.");
}

// 11. Update verticals.json status
console.log("11. Updating registry...");
const index = loadVerticalsIndex();
const verticalEntry = index.verticals.find((v) => v.slug === slug);
if (verticalEntry) {
  verticalEntry.status = "active";
  writeFileSync(
    join(HUB_ROOT, "registry", "verticals.json"),
    JSON.stringify(index, null, 2) + "\n"
  );
}

// 12. Create CRM agent via setup-agent
console.log("12. Creating CRM agent...");
try {
  execSync(`npm run setup-agent -- ${slug}`, {
    cwd: HUB_ROOT,
    stdio: "inherit",
  });

  // 13. Re-read config with updated publicId and regenerate vertical.config.ts
  console.log("13. Regenerating vertical.config.ts with agent publicId...");
  const updatedConfig = loadVerticalConfig(slug);
  const updatedVerticalConfigContent = `/**
 * Vertical Configuration — Single source of truth for this vertical site.
 * Generated by the verticals hub scaffold script from registry/${slug}.json.
 * Do NOT edit manually — re-run the scaffold to update.
 */

export interface VerticalConfig {
  slug: string;
  brandName: string;
  domain: string;
  tagline: string;
  description: string;

  agent: {
    publicId: string | null;
    backendUrl: string;
    widgetUrl: string;
    phoneNumber: string | null;
  };

  theme: {
    primary: string;
    accent: string;
    success: string;
    warning: string;
  };

  industry: {
    name: string;
    shortName: string;
    avgTicket: string;
    painPoint: string;
    projectTypes: string[];
    commonSoftware: string[];
    leadSources: string[];
  };

  seo: {
    primaryKeywords: string[];
    metaPixelId: string | null;
  };

  social: Record<string, string>;
  calcomLink: string | null;
  relatedVerticals: Array<{
    name: string;
    domain: string;
    slug: string;
  }>;
}

export const config: VerticalConfig = ${JSON.stringify(
    {
      slug: updatedConfig.slug,
      brandName: updatedConfig.brandName,
      domain: updatedConfig.domain,
      tagline: updatedConfig.tagline,
      description: updatedConfig.description,
      agent: {
        publicId: updatedConfig.agent.publicId,
        backendUrl: updatedConfig.agent.backendUrl,
        widgetUrl: `${updatedConfig.agent.backendUrl}/widget/v1/widget.js`,
        phoneNumber: updatedConfig.agent.phoneNumber,
      },
      theme: updatedConfig.theme,
      industry: updatedConfig.industry,
      seo: {
        primaryKeywords: updatedConfig.seo.primaryKeywords,
        metaPixelId: updatedConfig.seo.metaPixelId,
      },
      social: updatedConfig.social,
      calcomLink: updatedConfig.calcomLink,
      relatedVerticals: updatedConfig.relatedVerticals,
    },
    null,
    2
  )};
`;
  writeFileSync(
    join(updatedConfig.repoDir, "src", "lib", "vertical.config.ts"),
    updatedVerticalConfigContent
  );

  // 14. Update .env.local with the real publicId
  console.log("14. Updating .env.local with agent publicId...");
  writeFileSync(
    join(updatedConfig.repoDir, ".env.local"),
    `BACKEND_URL=${updatedConfig.agent.backendUrl}\nAGENT_PUBLIC_ID=${updatedConfig.agent.publicId || ""}\nSITE_DOMAIN=${updatedConfig.domain}\n`
  );

  // 15. Rebuild with the real publicId
  console.log("15. Rebuilding with agent configured...");
  try {
    execSync("npm run build", { cwd: updatedConfig.repoDir, stdio: "inherit" });
  } catch {
    console.error("\n   WARNING: Rebuild failed. Fix errors before deploying.");
  }
} catch {
  console.error(
    "\n   WARNING: Agent setup failed. Run `npm run setup-agent -- " +
      slug +
      "` manually after fixing the issue."
  );
}

// 16. Create GitHub repo and push
console.log("16. Creating GitHub repo...");
const repoName = config.brandName.toLowerCase().replace(/[^a-z0-9-]/g, "");
try {
  execSync("git add -A", { cwd: config.repoDir, stdio: "pipe" });
  execSync('git commit -m "Initial commit: scaffold from verticals hub"', {
    cwd: config.repoDir,
    stdio: "pipe",
  });
  execSync(
    `gh repo create Gahroot/${repoName} --public --source . --push`,
    { cwd: config.repoDir, stdio: "inherit" }
  );
  console.log(`   GitHub repo created: https://github.com/Gahroot/${repoName}`);
} catch {
  console.error(
    "\n   WARNING: GitHub repo creation failed. Create it manually."
  );
}

// 17. Link to Vercel and deploy
console.log("17. Linking to Vercel and deploying...");
try {
  // Link to Vercel (creates new project)
  execSync("vercel link --yes", { cwd: config.repoDir, stdio: "inherit" });

  // Read the generated .vercel/project.json to get project ID
  const vercelProjectPath = join(config.repoDir, ".vercel", "project.json");
  if (existsSync(vercelProjectPath)) {
    const vercelProject = JSON.parse(readFileSync(vercelProjectPath, "utf-8"));
    // Update registry with Vercel IDs
    const registryPath = join(HUB_ROOT, "registry", `${slug}.json`);
    const registryConfig = JSON.parse(readFileSync(registryPath, "utf-8"));
    registryConfig.vercel.projectId = vercelProject.projectId;
    registryConfig.vercel.teamId = vercelProject.orgId;
    writeFileSync(registryPath, JSON.stringify(registryConfig, null, 2) + "\n");
    console.log(`   Vercel project linked: ${vercelProject.projectId}`);
  }

  // Add custom domain
  console.log(`18. Adding custom domain: ${config.domain}...`);
  try {
    execSync(`vercel domains add ${config.domain}`, {
      cwd: config.repoDir,
      stdio: "inherit",
    });
    // Also add www subdomain
    execSync(`vercel domains add www.${config.domain}`, {
      cwd: config.repoDir,
      stdio: "inherit",
    });
    console.log(`   Domains configured: ${config.domain}, www.${config.domain}`);
  } catch {
    console.error(
      `\n   WARNING: Domain setup failed. Add ${config.domain} manually via vercel domains.`
    );
  }

  // Production deploy
  console.log("19. Running production deploy...");
  execSync("vercel deploy --prod", {
    cwd: config.repoDir,
    stdio: "inherit",
  });

  // Update lastDeployedAt
  const registryPath = join(HUB_ROOT, "registry", `${slug}.json`);
  const registryConfig = JSON.parse(readFileSync(registryPath, "utf-8"));
  registryConfig.lastDeployedAt = new Date().toISOString().split("T")[0];
  writeFileSync(registryPath, JSON.stringify(registryConfig, null, 2) + "\n");

  console.log("   Production deploy complete!");
} catch {
  console.error(
    "\n   WARNING: Vercel deploy failed. Run `/deploy " +
      slug +
      "` manually."
  );
}

// Connect GitHub repo to Vercel project
console.log("20. Connecting GitHub repo to Vercel...");
try {
  execSync(
    `vercel git connect Gahroot/${repoName}`,
    { cwd: config.repoDir, stdio: "inherit" }
  );
  console.log("   GitHub repo connected to Vercel for auto-deploys.");
} catch {
  console.error(
    "\n   WARNING: GitHub-Vercel connection failed. Connect manually in Vercel dashboard."
  );
}

console.log(`\n✅ Vertical "${config.brandName}" fully deployed!`);
console.log(`   Repo: https://github.com/Gahroot/${repoName}`);
console.log(`   Site: https://${config.domain}`);
console.log("\nNext steps:");
console.log("  1. Configure DNS for " + config.domain + " (point to Vercel)");
console.log("  2. Add content (best-for, alternatives, blog)");
