#!/usr/bin/env tsx
/**
 * Sync cross-links across all active vertical sites.
 *
 * For each active vertical, generates a crosslinks.ts file
 * containing links to all OTHER active verticals.
 *
 * Usage: tsx scripts/sync-crosslinks.ts
 */

import { existsSync, writeFileSync } from "fs";
import { join } from "path";
import { loadVerticalConfig, loadVerticalsIndex } from "./lib/config";

const index = loadVerticalsIndex();
const activeVerticals = index.verticals.filter((v) => v.status === "active");

if (activeVerticals.length === 0) {
  console.log("No active verticals found.");
  process.exit(0);
}

console.log(`\nSyncing cross-links for ${activeVerticals.length} active vertical(s):\n`);

// Load all active configs
const configs = activeVerticals.map((v) => loadVerticalConfig(v.slug));

for (const config of configs) {
  if (!existsSync(config.repoDir)) {
    console.log(`  SKIP: ${config.brandName} (repo not found)`);
    continue;
  }

  // Build crosslinks for this vertical (all OTHER active verticals)
  const crosslinks = configs
    .filter((c) => c.slug !== config.slug)
    .map((c) => ({
      name: c.brandName,
      domain: c.domain,
      url: `https://${c.domain}`,
      tagline: c.tagline,
    }));

  const content = `/**
 * Cross-links to other vertical sites in the network.
 * Auto-generated by the verticals hub sync-crosslinks script.
 * Do NOT edit manually.
 */

export interface CrossLink {
  name: string;
  domain: string;
  url: string;
  tagline: string;
}

export const crosslinks: CrossLink[] = ${JSON.stringify(crosslinks, null, 2)};
`;

  const targetPath = join(config.repoDir, "src", "lib", "crosslinks.ts");
  writeFileSync(targetPath, content);
  console.log(`  ${config.brandName}: ${crosslinks.length} cross-links written`);
}

console.log("\nDone.");
